In [1]:
# Import modules
import numpy as np
import pandas as pd
from geopy import distance

# Import PyGad
import pygad

In [2]:
#constant data
maxCapacity = 150.0 # capacidad del vehiculo en litros
consumption = 7.0 # consumo del vehiculo en Km por litro

In [3]:
# leer los datos del archivo Excel y almacenarlos en un DataFrame
df = pd.read_excel('ciudades_Bahia.xlsx')

# generate cities 
print('cities:')
print('| id |   lat   |   long  |   cost  |')
cities = []

prices = df.iloc[:, 3].values

# recorrer el DataFrame y agregar cada fila como una tupla a la lista de ciudades
for index, row in df.iterrows():
    city = index
    lat = row[1]
    long = row[2]
    C = row[3]
    cities.append((city, lat, long, C))
    print('|%4i|%9.4f|%9.4f|%9.4f|' % (city, lat, long, C))

cities:
| id |   lat   |   long  |   cost  |
|   0| -12.1356| -38.4192|   3.3070|
|   1| -12.1528| -44.9900|   3.6540|
|   2| -14.2036| -41.6653|   3.6460|
|   3| -14.0694| -42.4750|   3.6880|
|   4| -12.6975| -38.3242|   3.3580|
|   5| -16.3775| -39.5803|   3.5260|
|   6| -12.2667| -38.9667|   3.3460|
|   7| -14.2233| -42.7814|   3.6200|
|   8| -14.7936| -39.0395|   3.7610|
|   9| -12.1583| -39.7372|   3.3040|
|  10| -11.3042| -41.8558|   3.6500|
|  11| -14.7856| -39.2803|   3.5990|
|  12| -17.0392| -39.5311|   3.5200|
|  13| -11.1814| -40.5137|   3.5920|
|  14| -13.5306| -39.9708|   3.3360|
|  15| -13.8588| -40.0851|   3.5970|
|  16|  -9.4139| -40.5028|   3.6680|
|  17| -12.8944| -38.3272|   3.2700|
|  18| -13.6428| -41.8408|   3.7210|
|  19|  -9.4061| -38.2147|   3.6830|
|  20| -14.5297| -40.3653|   3.3800|
|  21| -16.4497| -39.0647|   4.0670|
|  22| -12.9711| -38.5108|   3.3990|
|  23| -12.9689| -39.2614|   3.3400|
|  24| -10.4614| -40.1894|   3.4810|
|  25| -11.6642| -39.0075|   3

In [4]:
N = len(cities) # Numero de ciudades
#Matriz con distancias
distance_matrix = np.zeros((N, N))
for i, start in enumerate(cities):
    for j, end in enumerate(cities):
        coord1 = (start[1], start[2]) # coordenadas de latitud y longitud del primer punto
        coord2 = (end[1], end[2]) # coordenadas de latitud y longitud del segundo punto
        distance_matrix[i][j] = distance.distance(coord1, coord2).km # distancia entre los dos puntos en Km
distance_matrix

array([[  0.        , 715.18344924, 419.72774151, 489.06551738,
         63.01732422, 485.76600052,  61.31959795, 526.25259457,
        301.64743009, 143.48289319, 385.76076336, 307.64887984,
        555.62433208, 251.59103198, 228.44791546, 262.68577153,
        377.56185419,  84.5449818 , 407.06485372, 302.74013051,
        338.53143037, 482.38145574,  92.96937053, 129.90815943,
        267.66889169,  82.62709637,  71.80221339, 614.15144374,
        153.94787436, 399.87860116],
       [715.18344924,   0.        , 425.86890697, 345.43930529,
        727.24793117, 747.70750784, 655.55258863, 331.34063187,
        707.37076833, 571.70301776, 354.31380148, 683.34403155,
        798.75773038, 499.74527307, 565.74250327, 564.5435198 ,
        576.68542844, 728.77215773, 379.43849633, 800.77860428,
        565.79328964, 796.53523756, 709.87509559, 629.0359239 ,
        556.46026394, 653.9517807 , 719.36153653, 820.61124984,
        656.44385733, 540.34063723],
       [419.72774151, 425.8689

!!!! Aqui iria el generador de caminos (enjambre de particulas)

De momento usaremos un camino fijo

In [5]:
path_0 = np.array([10,  1,  7,  3, 18,  2, 29, 20, 15, 14, 28, 23,  9, 13, 24, 16, 19, 25,  6,  0,  4, 26, 17, 22,  8, 11, 21,  5, 12, 27])
km_0 = 3130.1393740079825

In [6]:
# calculation of the minimum cost for a path
sorted_prices = np.sort(prices)
def minimun_path_cost(km):
    liters = km / consumption
    liters_aux = liters
    cost = 0
    for i in range(len(sorted_prices)):
        if liters_aux > maxCapacity:
            cost += maxCapacity * sorted_prices[i]
            liters_aux -= maxCapacity
        else:
            cost += liters_aux * sorted_prices[i]
            return cost

min_cost_0 = minimun_path_cost(km_0)    
min_cost_0

1470.3757845317677

In [7]:
# prices of the path
def path_prices(path):
    prices_arr = np.zeros(len(path))
    for i in range(len(path)):
        prices_arr[i] = prices[path[i]]
    return prices_arr
    

prices_0 = path_prices(path_0)
prices_0

array([3.65 , 3.654, 3.62 , 3.688, 3.721, 3.646, 3.291, 3.38 , 3.597,
       3.336, 3.532, 3.34 , 3.304, 3.592, 3.481, 3.668, 3.683, 3.443,
       3.346, 3.307, 3.358, 3.367, 3.27 , 3.399, 3.761, 3.599, 4.067,
       3.526, 3.52 , 3.545])

In [35]:
path = path_0
path_price = prices_0
min_cost = min_cost_0

def cost_func(solution):
    
    tank = 0.0
    cost = 0.0
    for i in range(len(solution)): # len(solution) = nuber of genes = len(path)-1
        distance_km = distance_matrix[path[i]][path[i+1]]
        distance_liters = distance_km / consumption
        if solution[i] == False: # minimum refueling to reach the next point
            if (distance_liters > tank):
                cost += (distance_liters - tank) * path_price[i]
                tank += distance_liters - tank
                
        else: # refueling to get to the next cheapest point without exceeding the limit
            liters_aux = distance_liters
            if (i <= len(solution)-1):
                for j in range(i+1, len(solution)):
                    if (path_price[j] < path_price[j+1]):
                        liters_aux += distance_matrix[path[j]][path[j+1]] / consumption
                    else:
                        break
                if liters_aux + tank > 150.0:
                    liters_aux = 150.0 - tank

            if (liters_aux > tank):
                cost += (liters_aux - tank) * path_price[i]
                tank += liters_aux - tank
                
        tank -= distance_liters
                  
    return cost

unos = np.ones(28, dtype=int)
ceros = np.zeros(28, dtype=int)
print(cost_func(unos))
print(cost_func(ceros))

1574.4056187903343
1560.8338896493526


In [48]:

def fitness_func(ga_instance, solution, solution_idx):
    
    cost = cost_func(solution)

    x = (cost - min_cost) / min_cost
    if x <= 0:
        fitness = 1
    else:
        fitness = np.exp(-10*x)
                  
    return fitness

print(fitness_func(unos,unos,unos))
print(fitness_func(ceros,ceros,ceros))

0.49287233997553725
0.5405306205839703


In [63]:
fitness_function = fitness_func

num_generations = 1000
num_parents_mating = 2

sol_per_pop = 8
num_genes = len(path) - 1


parent_selection_type = "sss"
keep_parents = 1

crossover_type = "single_point"

mutation_type = "random"
mutation_percent_genes = 10

In [64]:
N = len(path)
gene_space = [[0, 1] for _ in range(num_genes)]
initial_population = np.array([np.ones((num_genes)) for i in range(sol_per_pop)])

In [65]:
ga_instance = pygad.GA(num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes,
                       gene_space=gene_space,
                       initial_population=initial_population)

In [66]:
ga_instance.initial_population

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1

In [67]:
ga_instance.run()

In [68]:
solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution))
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))
print("Cost of the best solution: {cost}".format(cost=cost_func(solution)))


Parameters of the best solution : [1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0.
 0. 1. 1. 0. 0.]
Fitness value of the best solution = 0.48049967324118664
Cost of the best solution: 1578.1438502595956
